# Form implementation generated from reading ui file 'password_gen.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswordGenerate(object):
    def setupUi(self, PasswordGenerate):
        PasswordGenerate.setObjectName("PasswordGenerate")
        PasswordGenerate.resize(368, 321)
        font = QtGui.QFont()
        font.setPointSize(20)
        PasswordGenerate.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordGenerate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        self.retranslateUi(PasswordGenerate)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerate)

    def retranslateUi(self, PasswordGenerate):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerate.setWindowTitle(_translate("PasswordGenerate", "密碼生成小程序"))
        self.pushButton.setText(_translate("PasswordGenerate", "生成一個新的密碼"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordGenerate = QtWidgets.QDialog()
    ui = Ui_PasswordGenerate()
    ui.setupUi(PasswordGenerate)
    PasswordGenerate.show()
    sys.exit(app.exec())
