# Form implementation generated from reading ui file 'd:\python\python-100-days\pyqt\chapter 2\password_gen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswordGenerate(object):
    def setupUi(self, PasswordGenerate):
        PasswordGenerate.setObjectName("PasswordGenerate")
        PasswordGenerate.resize(603, 312)
        font = QtGui.QFont()
        font.setPointSize(20)
        PasswordGenerate.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordGenerate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_site = QtWidgets.QLineEdit(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_site.setFont(font)
        self.lineEdit_site.setObjectName("lineEdit_site")
        self.horizontalLayout.addWidget(self.lineEdit_site)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_upper = QtWidgets.QCheckBox(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.checkBox_upper.setFont(font)
        self.checkBox_upper.setObjectName("checkBox_upper")
        self.horizontalLayout_2.addWidget(self.checkBox_upper)
        self.checkBox_lower = QtWidgets.QCheckBox(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.checkBox_lower.setFont(font)
        self.checkBox_lower.setObjectName("checkBox_lower")
        self.horizontalLayout_2.addWidget(self.checkBox_lower)
        self.checkBox_number = QtWidgets.QCheckBox(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.checkBox_number.setFont(font)
        self.checkBox_number.setObjectName("checkBox_number")
        self.horizontalLayout_2.addWidget(self.checkBox_number)
        self.checkBox_puc = QtWidgets.QCheckBox(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.checkBox_puc.setFont(font)
        self.checkBox_puc.setObjectName("checkBox_puc")
        self.horizontalLayout_2.addWidget(self.checkBox_puc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit_result = QtWidgets.QLineEdit(parent=PasswordGenerate)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_result.setFont(font)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.verticalLayout.addWidget(self.lineEdit_result)

        self.retranslateUi(PasswordGenerate)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerate)

    def retranslateUi(self, PasswordGenerate):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerate.setWindowTitle(_translate("PasswordGenerate", "密碼生成小程序"))
        self.label.setText(_translate("PasswordGenerate", "網站名稱:"))
        self.checkBox_upper.setText(_translate("PasswordGenerate", "大寫字母"))
        self.checkBox_lower.setText(_translate("PasswordGenerate", "小寫字母"))
        self.checkBox_number.setText(_translate("PasswordGenerate", "數字"))
        self.checkBox_puc.setText(_translate("PasswordGenerate", "標點符號"))
        self.pushButton.setText(_translate("PasswordGenerate", "生成一個新的密碼"))
