# Form implementation generated from reading ui file 'bmi_compute.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BMI_compute(object):
    def setupUi(self, BMI_compute):
        BMI_compute.setObjectName("BMI_compute")
        BMI_compute.resize(462, 339)
        BMI_compute.setStyleSheet("*{\n"
"    font-size : 14px\n"
"}\n"
"\n"
"QPushButton{\n"
"    height : 50px\n"
"}\n"
"\n"
"QLabel{\n"
"    color : blue\n"
"}")
        self.widget = QtWidgets.QWidget(parent=BMI_compute)
        self.widget.setGeometry(QtCore.QRect(30, 40, 321, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_height = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.horizontalLayout.addWidget(self.lineEdit_height)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_weight = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.horizontalLayout_2.addWidget(self.lineEdit_weight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setStyleSheet("*{\n"
"    font : bold\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setStyleSheet("*{\n"
"    background-color : rgb(170, 255, 0)\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3.setStretch(0, 8)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("*{\n"
"    background-color:rgb(255, 255, 127)\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_result = QtWidgets.QLabel(parent=self.widget)
        self.label_result.setStyleSheet("*{\n"
"    background-color:rgb(255, 255, 127)\n"
"}")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 8)
        self.verticalLayout_3.setStretch(1, 2)

        self.retranslateUi(BMI_compute)
        QtCore.QMetaObject.connectSlotsByName(BMI_compute)

    def retranslateUi(self, BMI_compute):
        _translate = QtCore.QCoreApplication.translate
        BMI_compute.setWindowTitle(_translate("BMI_compute", "人體BMI計算器"))
        self.label.setText(_translate("BMI_compute", "請輸入身高 (cm) :"))
        self.label_2.setText(_translate("BMI_compute", "請輸入體重 (kg) :"))
        self.pushButton.setText(_translate("BMI_compute", "計算BMI"))
        self.label_5.setText(_translate("BMI_compute", "提示:"))
        self.label_3.setText(_translate("BMI_compute", "你的計算結果 :"))
        self.label_result.setText(_translate("BMI_compute", "BMI : 27.18"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMI_compute = QtWidgets.QDialog()
    ui = Ui_BMI_compute()
    ui.setupUi(BMI_compute)
    BMI_compute.show()
    sys.exit(app.exec())
